DROP DATABASE IF EXISTS pantry_db;
CREATE DATABASE pantry_db;

USE pantry_db;

CREATE TABLE user (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(30) NOT NULL,
	email VARCHAR(40) UNIQUE NOT NULL,
	password VARCHAR(30) NOT NULL,
	location VARCHAR(40) NOT NULL
);

CREATE TABLE food_post (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	image VARCHAR(50) NOT NULL,
	title VARCHAR (30) NOT NULL,
	description VARCHAR(40) NOT NULL,
	desired_item VARCHAR(30) NOT NULL,
	user_id INT UNSIGNED NOT NULL,
	CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
);

CREATE TABLE trade_request (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	buyer_id INT UNSIGNED NOT NULL,
	CONSTRAINT fk_buyer FOREIGN KEY (buyer_id) REFERENCES user(id) ON DELETE CASCADE,
	seller_id INT UNSIGNED NOT NULL,
	CONSTRAINT fk_seller FOREIGN KEY (seller_id) REFERENCES user(id) ON DELETE CASCADE,
	food_post_id INT UNSIGNED NOT NULL,
	CONSTRAINT fk_food_post FOREIGN KEY (food_post_id) REFERENCES food_post(id) ON DELETE CASCADE,
	status VARCHAR(30) NOT NULL
);